FROM registry.cn-hangzhou.aliyuncs.com/dmcloudv2/goland-1.9-alpine
WORKDIR /opt/udp
RUN go get -d -v github.com/1lann/udp-forward
COPY udp_server.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main -v udp_server.go .

FROM scratch
COPY ca-certificates.crt /etc/ssl/certs/
WORKDIR /root/
COPY --from=0 /opt/udp .
EXPOSE 2022/udp
ENTRYPOINT ["./main"]