#FROM registry.cn-hangzhou.aliyuncs.com/dmcloudv2/goland-1.9-alpine
FROM golang:1.9.4-alpine3.7
RUN apk add --no-cache git
WORKDIR /opt/udp
RUN go get -d -v github.com/astaxie/beego/logs \
&& go get -d -v github.com/jinzhu/gorm \
&& go get -d -v github.com/jinzhu/gorm/dialects/mysql \
&& go get -d -v github.com/1lann/udp-forward
COPY core $GOPATH/src/udp-proxy/core
COPY main.go .
RUN ls -al $GOPATH/src/udp-proxy/core
RUN ls -al /opt/udp
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main -v main.go

FROM busybox:1.28
ENV GODEBUG=netdns=go
COPY ca-certificates.crt /etc/ssl/certs/
WORKDIR /root/
COPY --from=0 /opt/udp .
EXPOSE 4042/udp
EXPOSE 8888/tcp
ENTRYPOINT ["./main"]
